export default {
  FILTER_MODULE: 'filter/',

  // actions

  GET_CAR_BRANDS: 'GET_CAR_BRANDS',
  GET_BRAND_MODELS: 'GET_BRAND_MODELS',
  GET_FILTERS: 'GET_FILTERS',

  // mutations

  SET_FILTERS: 'SET_FILTERS',
  SET_CAR_BRANDS: 'SET_CAR_BRANDS',
  SET_BRANDS_MODELS: 'SET_BRANDS_MODELS',
  SET_YEARS: 'SET_YEARS'
}
